### ISSUE TITLE
Upgrade hadoop client to fix vulnerability

### ISSUE THREAD

**Issue by kaklakariada** [exasol/parquet-io-java#50]
Upgrade Hadoop as soon as a fixed version is available.
See https://ossindex.sonatype.org/vulnerability/sonatype-2022-5732
```
Error:  Failed to execute goal org.sonatype.ossindex.maven:ossindex-maven-plugin:3.2.0:audit (default-cli) on project parquet-io-java: Detected 1 vulnerable components:
Error:    org.apache.hadoop:hadoop-hdfs-client:jar:3.3.4:compile; https://ossindex.sonatype.org/component/pkg:maven/org.apache.hadoop/hadoop-hdfs-client@3.3.4?utm_source=ossindex-client&utm_medium=integration&utm_content=1.8.1
Error:      * 1 vulnerability found (8.6); https://ossindex.sonatype.org/vulnerability/sonatype-2022-5732
```

Check https://search.maven.org/artifact/org.apache.hadoop/hadoop-hdfs-client for new Hadoop versions.

**Comment by ckunki** [comment]
Vulnerability is reported for reading XML data while payload for [virtual-schema-common-document-files](https://github.com/exasol/virtual-schema-common-document-files) only supports formats json, csv, and parquet.

**Comment by redcatbear** [comment]
I just checked and 3.3.4 is still the latest version of the `haddop-hdfs-client`: See [release list](https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs-client/).

**Comment by redcatbear** [comment]
Still no new release of the Hadoop HDFS Client.

**Comment by redcatbear** [comment]
Still no new release of the Hadoop HDFS Client.
