### ISSUE TITLE
Issue with reading UINT32 and UINT64 columns 

### ISSUE THREAD

**Issue by rajarahul12** [exasol/parquet-io-java#59]
Hi, I am trying the Parquet reader with a parquet file having UNIT32 and UNIT 64 types
When I read a row - I am getting -1 for these two column types.

Dependency used:
```
<groupId>com.exasol</groupId>
<artifactId>parquet-io-java</artifactId>
 <version>2.0.3</version>
```

I am sharing the parquet file used:
[int_types.parquet.zip](https://github.com/exasol/parquet-io-java/files/11556361/int_types.parquet.zip)

This is the output I am seeing from the reader
`Row(values=[255,65535,-1,-1,-128,-32768])
`

But the file contents are this
<img width="849" alt="Screenshot 2023-05-24 at 8 58 58 PM" src="https://github.com/exasol/parquet-io-java/assets/26481390/f7ceab30-8cd8-4428-a2ed-3e5e0b84f381">

**Comment by rajarahul12** [comment]
Can anyone suggest a solution to this? @kaklakariada @morazow

**Comment by morazow** [comment]
Hello @rajarahul12,

Thanks for the feedback!

We are going to look into it. But most probably the Parquet types `UINT32` and `UINT64` are not supported. 

Thanks for providing an example Parquet file, we are going to check it.

**Comment by morazow** [comment]
Hello @rajarahul12,

Thanks for the feedback! 

Indeed the conversion from the Parquet unsigned types are not implemented in the library. However, are not going to add a support for them.

[Unsigned types](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#deprecated-integer-convertedtype) are not supported in latest Parquet versions.

However, you could represent the unsigned values using the base types.

Here is an example:

```
message test {
         required int32 col_uint8;
         required int32 col_uint16;
         required int64 col_uint32;
         required binary col_uint64 (DECIMAL(20,0));
}
```

You could write large values as decimal data. See the example test case in this file: [RowParquetReaderUnsignedIntegerTypesTest.scala](https://github.com/exasol/parquet-io-java/blob/question/%2359-usigned-types/src/test/scala/com/exasol/parquetio/reader/RowParquetReaderUnsignedIntegerTypesTest.scala).

Please let us know if this helps you use case.

**Comment by morazow** [comment]
Hello @rajarahul12,

We are going to close this issue for now. Please let us know if you have more questions.
