### ISSUE TITLE
ParquetReader does not exist

### ISSUE THREAD

**Issue by davidfstein** [exasol/parquet-io-java#60]
When trying to compile the example in the readme I get the following:

[ERROR] ~/testpar/App.java:[24,19] cannot find symbol
[ERROR] symbol:   class ParquetReader

How can I fix this?

**Comment by morazow** [comment]
Hello @davidfstein,

Thanks for the feedback!

I think you could import the `ParquetReader` class:

```java
import org.apache.parquet.hadoop.ParquetReader;
```

For this you may need to also add the Parquet dependency.

```xml
<dependency>
       <groupId>org.apache.parquet</groupId>
       <artifactId>parquet-hadoop</artifactId>
       <version>VERSION</version>
</dependency>
```

**Comment by morazow** [comment]
We are going to close this ticket. 

Please feel free to open another issue if you have any questions.
